### ISSUE TITLE
Header file `partitioning.h` is missing

### ISSUE THREAD

**Issue by melhindi** [agora-ecosystem/tee-bench#1]
When compiling the code the following compile errors occur:
```
Enclave/Partitioning/partitioning.cpp:1:10: fatal error: partitioning.h: No such file or directory
    1 | #include "partitioning.h"

Enclave/TrustedJoins/secure_joins.cpp:21:10: fatal error: partitioning.h: No such file or directory
   21 | #include "partitioning.h"
```

it is also not possible to locate the file `partitioning.h` in the repository, it seems to be missing. Could you pls. add it.

**Comment by kai-chi** [comment]
Hi! 
Thanks a lot for reporting the issue. These files were remnants from some development. I removed them and fixed the remaining errors. The code compiles now on my machine. Let me know if you can compile it now.

**Comment by melhindi** [comment]
Hi,
thanks for fixing it, now the code also compiles on my machine.
