### ISSUE TITLE
Please update readme

### ISSUE THREAD

**Issue by melhindi** [agora-ecosystem/tee-bench#2]
Hi, it seems that the instructions in the following line of the README are out-dated.
```
Clone the repository usig git-lfs:
$ git lfs clone https://github.com/agora-ecosystem/tee-bench-dev.git
```
Since there is no publicly visible dev branch, I assume it should point to `https://github.com/agora-ecosystem/tee-bench.git`

Further, when using newer `git` versions, just using `git clone` instead of `git lfs clone` is sufficient (git-lfs still needs to be installed, tough). On newer git version, users will see the following deprecation message:
```
 WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'
```

**Comment by kai-chi** [comment]
Hi!

Thank you for reporting the issue! I updated the README file with your suggestions.
